"""changed way income is calculated so will remove iincome column

Revision ID: 2298d7a62406
Revises: 8d856f31b4a9
Create Date: 2024-11-29 13:31:50.325832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2298d7a62406'
down_revision = '8d856f31b4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
