"""added  achievement code to achiievement model

Revision ID: 2e9c019de24c
Revises: 6c4ed28fd1bc
Create Date: 2024-12-22 13:11:58.262580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9c019de24c'
down_revision = '6c4ed28fd1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
