"""added animal puchasing

Revision ID: 6c4ed28fd1bc
Revises: e0c753874d23
Create Date: 2024-12-11 13:53:57.010809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4ed28fd1bc'
down_revision = 'e0c753874d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
