"""added claiimed  to completions

Revision ID: c377162ebace
Revises: 2e9c019de24c
Create Date: 2024-12-23 15:34:01.952061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c377162ebace'
down_revision = '2e9c019de24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completes', schema=None) as batch_op:
        batch_op.drop_column('claimed')

    # ### end Alembic commands ###
