"""3

Revision ID: c7a2422b9eb2
Revises: 57d89b569626
Create Date: 2024-11-18 18:55:51.206786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a2422b9eb2'
down_revision = '57d89b569626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('income')

    # ### end Alembic commands ###
