"""empty message

Revision ID: e0c753874d23
Revises: 2298d7a62406
Create Date: 2024-12-03 00:36:06.518509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c753874d23'
down_revision = '2298d7a62406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('animal_price')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
